### PR TITLE
Add license and repository metadata

### PR DESCRIPTION
**Pull request by shivamchadha**
Added license, and repository field in activity.info.
This is a part of GCI task.

### CODE REVIEW

**Comment by shivamchadha** [comment]
@leonardcj  please take a look.

**Comment by quozl** [comment]
Review.  Won't merge, sorry.

- [x] please use COPYING for the file name, not LICENSE.txt,
- [x] please use GPLv2 text in COPYING, because that's what the license is in the activity.info and <s>most</s> _all_ of the python source files,
- [x] please use the Sugar Labs repository in the activity.info file, not your own.

Also, please improve your commit messages, see [making commits](https://developer.sugarlabs.org/contributing.md.html#making%20commits).  Have a look at the previous commits in the repository to get an idea for the style used by the developers.

**Comment by quozl** [comment]
Thanks, much improved.

Next couple of problems;

- [x] there is still a LICENSE.txt file added by your commits on this pull request,
- [x] the text in COPYING is not the same text as the original license, in particular all the indentation and line wrapping has been lost.  GitHub and many downstream distributions use an md5sum or sha256sum of the COPYING file to quickly check the license; that won't work with your versions.

**Comment by quozl** [comment]
Oops, my mistake.  Saw that `activity.info` declared only GPLv2+, and there was no source that uses LGPLv2 in the activity, so there was no need to include an LGPLv2 license long text.  Removed COPYING.LGPLv2, amended commit and force pushed as 9bd2599ee46e1af932cd947bb993673872fae952.

**Comment by shivamchadha** [comment]
Thank you.

**Pull request merged**
