### PR TITLE
Fixing PyGIWarning

### PR DESCRIPTION
**Pull request by Aniket21mathur**

### CODE REVIEW

**Comment by quozl** [comment]
Why isn't Gdk also added?

**Comment by Aniket21mathur** [comment]
Surprisingly there were no warnings related to Gdk in my console. But as it is a good practice to specify versions before importing, also adding Gdk.Thanks!

**Comment by quozl** [comment]
Thanks.  It was your other pull request https://github.com/sugarlabs/memorize-activity/pull/22/commits/f08414b1b8c442c1f36f7e7f7cd9ec81c2c6e8d8 which was puzzling; 'cause if you had a PyGIWarning about Gdk in that activity, but not in this activity, I'm not sure why.  Mysteries shouldn't be left alone.  Did you use the same operating system version for testing both activities?  What was the version?

**Comment by Aniket21mathur** [comment]
I am not very sure but one of the possible reason for this might be this line 
` label.modify_fg(Gtk.StateType.NORMAL,
                            style.COLOR_TOOLBAR_GREY.get_gdk_color())`
in memorize-activity/createcardpanel.py which involved "gdk" instead of Gdk, while in this activity there is nothing like this.Also I gone through the source code of couple of other activities and found out the same.Again I am not very sure about this.
Thanks!

**Comment by quozl** [comment]
Thanks for checking.  I'm wondering if it is the ordering of imports; my preference is to import lower level modules first, and since Pango and Gtk both depend on Gdk, it would make more sense to import Gdk first.  Perhaps Pango embeds a require_version of Gdk, I haven't checked.  The activities may differ in the import order.  You didn't answer my other questions; did you use the same operating system version for testing both activities?  What was the version?

**Comment by Aniket21mathur** [comment]
Yes I used the same os Ubuntu 18.04 to test the activities.Thanks!

**Pull request merged**
