### PR TITLE
Port to Python 3 

### PR DESCRIPTION
**Pull request by ayushnawal**

### CODE REVIEW

**Comment by quozl** [comment]
Nothing I tried would work.  What was your test case?

**Comment by ayushnawal** [comment]
I just tested the activity before and after porting, it was working fine.
Here's a snapshot of the activity i am attaching after the changes made.

Screenshot from 2019-12-17 16-16-39

**Comment by ayushnawal** [comment]
I just tested the activity before and after porting, it was working fine.
Here's a snapshot of the activity i am attaching after the changes made.

Screenshot from 2019-12-17 16-22-40

**Comment by quozl** [comment]
Sure, it starts, it searches (sometimes), but do you have any successful downloads?  What was your test case?

**Comment by ayushnawal** [comment]
@quozl I didn't download, I just searched for the book and tested the URL, but now I noticed that i am getting a server error, saw this in logs after the search 
`from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;
`

I am unable to figure out what kind of error it is, can you please guide me a bit? Thanks!

**Comment by jdsimmons** [comment]
Nawal,

Judging from the message, it would appear that the URL you use to
download the book is improperly formatted and contains an ampersand
character (&). In URL's an ampersand has a specific meaning, so if you need
to put an ampersand in a URL that is *not *used for that purpose you need
to represent it some other way, perhaps as &amp;

https://www.w3schools.com/html/html_urlencode.asp

James Simmons

**Comment by quozl** [comment]
I agree.  You will need to diagnose and debug the problem.  If it does the same before porting, then we can keep this pull request open until it is fixed, then you can rebase.  If it doesn't do the same before porting, then something in the porting has caused it.  I usually won't merge porting pull requests unless the activity works properly.

**Comment by ayushnawal** [comment]
Agreed. I am trying to figure out.

**Comment by jdsimmons** [comment]
The search arguments for Internet Archive Advanced Search changed and broke this Activity. This has been corrected and the master branch has the changes.

**Pull request closed without merging**
