### PR TITLE
Port to Python3 and GLib

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
Tested works fine, but still #11 is blocking this PR.

### CODE REVIEW

**Comment by Saumya-Mishra9129** [comment]
Regarding #11 I know the reason , and I have handled these errors earlier also, but here is something different, 

> Failed to set text `search text` from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp

Sometimes there can be characters in uri , such that markup parser can fail to parse the markup. markup_escape_text should be used to escape text so that the markup parser will be able to  parse it, by GLib.markup_escape_text , less than, greater than, ampersand, etc. will be replaced with the corresponding entities.

But here , using above method in search_url returns an HTML page, which means we encountered an error while downloading csv, according to code. I couldn't find any other way to solve it.

 @chimosky You said here https://github.com/sugarlabs/getiabooks/commit/1d923ba5bebee5ac0aa035aa22223ef52c7f9125#r37931007

> I was able to fix the Gtk warning - #10 - thrown by the activity but the new search url doesn't download the csv search file, it instead leads to an advanced search page. 

What do you mean by advance search page, I couldn't get it completely.

**Comment by quozl** [comment]
I don't understand, sorry.  Please answer these questions;

* which line of code generates the error _Failed to set text `search text` from markup_?
* what is the string being passed to GTK?
* does the string contain markup directives?
* can the GTK widget be controlled (e.g. set_use_markup(False))?

**Comment by quozl** [comment]
> What do you mean by advance search page, I couldn't get it completely.

A URL or page on internet archive that is titled and styled as an advanced search, as opposed to a default or simple search.

**Comment by jdsimmons** [comment]
Saumya,

I wrote this Activity many years ago. The code uses HTTP GET code I copied
from the Read Activity. It is used twice: once to do a search and the
second time to download the book. The search is done as if it had come from
this page:

https://archive.org/advancedsearch.php

It returns results in CSV format.

When you do an HTTP GET the arguments are separated by ampersands (&). If
there is an ampersand in the title of a book you need to change it to &amp;
but you must NEVER change the & used to separate arguments. If you do you
might get the result you are seeing.

James Simmons

**Pull request closed without merging**
